### ISSUE TITLE
Added GitHub link and removed a broken CSS link

### ISSUE THREAD

**Issue by Tarster** [ACM-IGDTUW/Open-Source-Challenge#122]
For #93
So, My small contribution to this awesome initiative is that I can add a GitHub and Instagram link in the footer.

**Comment by lisa761** [comment]
Hey @Tarster, that's a great idea but someone has already come up with this :(

**Comment by Tarster** [comment]
Ohh, I haven't noticed it all but I have already implemented it for Instagram and GitHub.The one who had originally created the issue can also put LinkedIn link as I don't use that platform

**Comment by soumyaa1804** [comment]
I think it would be fair if you implement it for GitHub and let the other person implement it for Instagram and LinkedIn.

**Comment by Tarster** [comment]
yeah,ok that's fine for me.I will generate a new PR.

**Comment by lisa761** [comment]
You also edit your issue here to say that now you will be working on adding only the github link and removing the broken css link.

**Comment by Tarster** [comment]
Done
