### ISSUE TITLE
Is this perfect ?

### ISSUE THREAD

**Issue by mishra-shruti96** [ACM-IGDTUW/Open-Source-Challenge#15]
![image](https://user-images.githubusercontent.com/50775636/79160026-ba585780-7df6-11ea-993f-0ff7273c1af4.png)

![image](https://user-images.githubusercontent.com/50775636/79160042-c6441980-7df6-11ea-9e3d-d8d7641fe26f.png)

**Comment by soumyaa1804** [comment]
Yes, @mishra-shruti96! It's perfect! But add them in the comments of task 1 so it becomes easier for us to evaluate.

**Comment by mishra-shruti96** [comment]
> Yes, @mishra-shruti96! It's perfect! But add them in the comments of task 1 so it becomes easier for us to evaluate.

https://github.com/ACM-IGDTUW/Open-Source-Challenge/issues/11#issuecomment-613256589

**Comment by lisa761** [comment]
Closing this since the comment is already added on the relevant issue.
