### ISSUE TITLE
Can't push because 2FA enabled

### ISSUE THREAD

**Issue by Tarster** [ACM-IGDTUW/Open-Source-Challenge#24]
I can't push to the GitHub because I have 2FA enabled.I have enabled SSH.So I don't have any issue in pushing any repo that are created on my account i.e. by me.However ,I can't do the same for this challenge stuck on last command:
git push origin tarster-task2

**Comment by Tarster** [comment]
https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line

I needed to create a Access token and use it as a password instead of my usual account password.

**Comment by lisa761** [comment]
@Tarster Great that you found it on your own! I had that problem too.
