### ISSUE TITLE
Task2 - unable to use echo command

### ISSUE THREAD

**Issue by raksha009** [ACM-IGDTUW/Open-Source-Challenge#33]
![IMG-20200414-WA0009](https://user-images.githubusercontent.com/57195964/79201554-e3f49b80-7e55-11ea-95e3-e663d452216d.jpeg)

**Comment by raksha009** [comment]
How to solve this problem and create a new file !?

**Comment by raksha009** [comment]
![IMG-20200414-WA0009](https://user-images.githubusercontent.com/57195964/79201742-23bb8300-7e56-11ea-9a77-d5fd3983292b.jpeg)

**Comment by lisa761** [comment]
Hi, @raksha009, the Task-2 says that if you get an error follow a given set of command. Did you check? You are supposed to follow these and then try again:
```sh
git checkout master
git fetch upstream
git rebase upstream/master
git push origin master
git checkout <your-new-branch-name>
```

**Comment by raksha009** [comment]
Yes.. i did it.. that's when i tried again, it showed master branch upto date

**Comment by soumyaa1804** [comment]
The reason is that you are already in the `participants` directory and then you are asking to create a file inside participants. Either do `cd ..` and then run the echo command again or just type `echo $null >> <your-GitHub-username>.md`

**Comment by raksha009** [comment]
It worked. Thanks 😊
