### ISSUE TITLE
In challenge 3 the command provided is wrong

### ISSUE THREAD

**Issue by Tarster** [ACM-IGDTUW/Open-Source-Challenge#51]
In challenge 3,There was a typo to delete a branch the command should be
```
git branch -d <branch_name>
```
To see all branches that are available in the current git 
```
git branch
```

**Comment by Tarster** [comment]
https://stackoverflow.com/questions/2003505/how-do-i-delete-a-git-branch-locally-and-remotely#2003515

**Comment by lisa761** [comment]
Does `-D` not work for you? It was intentionally written instead of `-d` so that people do not get an error. That happens sometimes when the git does not realize that the branch has been merged or when your branch has not been merged at all.

**Comment by lisa761** [comment]
Like it says in the link you provided:
> The -d option is an alias for --delete, which only deletes the branch if it has already been fully merged in its upstream branch. You could also use -D, which is an alias for --delete --force, which deletes the branch "irrespective of its merged status." [Source: man git-branch]

Often times the merge status does not get detected by git unless you update and in that case, its better to use `-D` instead.

**Comment by lisa761** [comment]
Should I close this issue then, that is, if there is no more addition?

**Comment by Tarster** [comment]
Well I had made a typo itself in the issue that's why I had provided the link:
Origionally command given in the challenge was:
``` git -D <branch-name>```
which is giving the error.However the command provided below 
```git branch -D <branch-name>```
resolves the issue.
and You are correct ```-D``` will delete the branch irrespective of it's merged status

**Comment by lisa761** [comment]
Oh right! I misunderstood. Thank you, I have edited the Task. Good work there :)

**Comment by Tarster** [comment]
No problem, I am closing the issue now.
