### ISSUE TITLE
couldn't run the npm command

### ISSUE THREAD

**Issue by eternal-dreamer** [ACM-IGDTUW/Open-Source-Challenge#64]
![Screenshot (13)](https://user-images.githubusercontent.com/53971925/79316584-5ba7e200-7eb9-11ea-971f-1cbf66039b20.png)
![Screenshot (13)](https://user-images.githubusercontent.com/53971925/79316604-619dc300-7eb9-11ea-9ec1-ad93e77a7f3d.png)

**Comment by soumyaa1804** [comment]
@eternal-dreamer are you using Git bash? If yes, I would recommend you to either use command prompt or add some configurations in you Git bash using [this](https://stackoverflow.com/questions/35915832/how-come-npm-install-doesnt-work-on-git-bash).

**Comment by eternal-dreamer** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/53971925/79320671-066ecf00-7ebf-11ea-940b-48278405785c.png)

**Comment by soumyaa1804** [comment]
can you attach the output of `node --version` and `npm --version`?

**Comment by soumyaa1804** [comment]
You heck may check this as well https://stackoverflow.com/questions/17162308/node-js-error-cannot-find-module-express

**Comment by lisa761** [comment]
Closing this since you have submitted task-1. If you have any doubts feel free to re-open this issue.
