### ISSUE TITLE
Problem with the npm install command

### ISSUE THREAD

**Issue by saloniankita** [ACM-IGDTUW/Open-Source-Challenge#81]
While completing the first task, I encountered the problem with npm install command.
![Screenshot 2020-04-14 01 50 41](https://user-images.githubusercontent.com/56873389/79370204-e8ad7280-7f6f-11ea-89f7-a7d344c6f162.png)
![Screenshot 2020-04-14 01 50 49](https://user-images.githubusercontent.com/56873389/79370221-eba86300-7f6f-11ea-96cb-49444f3d7e2a.png)

**Comment by soumyaa1804** [comment]
@saloniankita Please have a look at a previously mentioned issue [here](https://github.com/ACM-IGDTUW/Open-Source-Challenge/issues/64). If you are facing the same errors see through the comment section for solutions. Let us know if your problem is different than the one mentioned above.

**Comment by lisa761** [comment]
@saloniankita, Closing this since you have made task submissions. If you want to discuss anything more regarding this, feel free to re-open.
