### ISSUE TITLE
Changing Card style and Images

### ISSUE THREAD

**Issue by mansi35** [ACM-IGDTUW/Open-Source-Challenge#94]
For #93 
We could change the images and posters for different events on the events page of the website. Also, we can change the card style for the events cards.

**Comment by lisa761** [comment]
Great! Could you elaborate a bit more. Such as what card style you would prefer? Why you think its better than the current scenario? What images you think would be better instead.

**Comment by lisa761** [comment]
Also, edit your description to include `For #93` so that this issue can generate a mention for that one and change your title to summarize your issue.

**Comment by soumyaa1804** [comment]
@mansi35, also please edit the heading of this issue so that it gives a very brief intro to the changes you'll like to suggest. And you need not include `For #93` in the heading but just in the beginning of your issue desciption.

**Comment by mansi35** [comment]
I think we can add one more feature to the existing card style. For example when we hover over it, it can change color so that it would add more focus on the topic you're looking at. And we can just change images for just trying something new for change.

**Comment by soumyaa1804** [comment]
This seems doable but it will require to change the whole theme of the cards as the date, time and location as they have light font colour. @lisa761 what do you think?

**Comment by lisa761** [comment]
@soumyaa1804 you are right, although @mansi35 already created a PR for this, so lets see that.
